
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

lovelace:
  mode: yaml
  


vacuum:
- platform: xiaomi_miio
  name: Xiaowa
  host: 192.168.1.96
  token: !secret xiaowa_token
  model: roborock.vacuum.e2
  

discovery:
  ignore:
    - yeelight

light:
 - platform: yeelight
   devices:
    192.168.1.95:
     name: Yeelight bulb
     #transition: 350
     #model: yeelink.light.mono1
     #token: !secret yeelight_token


sensor:
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use
    - type: processor_use
    - type: load_1m


- platform: template
  sensors:
    google_round_trip:
      friendly_name: Google ping
      value_template: "{{states.binary_sensor.google.attributes.round_trip_time_max | round(0)}}"
      unit_of_measurement: 'msec'
    cloudflare_round_trip:
      friendly_name: Cloudflare ping
      value_template: "{{states.binary_sensor.cloudflare.attributes.round_trip_time_max | round(0)}}"
      unit_of_measurement: 'msec'


telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_chat_vaselo
      - !secret telegram_chat_svitlanka


notify:
  - name: telegram_notify_vaselo
    platform: telegram
    chat_id: !secret telegram_chat_vaselo
  - name: telegram_notify_svitlanka
    platform: telegram
    chat_id: !secret telegram_chat_svitlanka


binary_sensor:
  - platform: ping
    name: google
    host: 8.8.8.8
    count: 2
    scan_interval: 10
  - platform: ping
    name: cloudflare
    host: 1.1.1.1
    count: 2
    scan_interval: 10
 